version: "3.8"

services:
  tms-line-provider:
    platform: linux/amd64
    build: .
    image: registry.gitlab.com/jostechnology/tms-line-provider:latest
    container_name: tms-line-provider
    restart: always
    network_mode: bridge

    ports:
      - "5002:5002"

    environment:
      - CENTER_ACCESS_KEY=${CENTER_ACCESS_KEY}
      - CENTER_URL=${CENTER_URL}
      - LINE_SECRET=${LINE_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
