version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: tms-line-provider-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - line-provider

  tms-line-provider:
    platform: linux/amd64
    build: .
    image: registry.gitlab.com/jostechnology/tms-line-provider:${TAG}
    container_name: tms-line-provider
    restart: always
    ports:
      - "8092:5002"
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SERVICE_BASE_URL=${SERVICE_BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    networks:
      - line-provider

networks:
  line-provider:
    driver: bridge