"""
app/routers/tracking.py

Public BFF for the tracking page.
Accepts a short-lived token (generated by TMS),
returns the tracking read shape: status timeline + current GPS + ETA.

Dev mode: returns a fixture so the frontend can be built without TMS.
Prod mode: proxies to TMS tracking read endpoint.

Toggle via env var:
  TRACKING_MODE=fixture   → return fixture (default if TMS_TRACKING_URL not set)
  TRACKING_MODE=proxy     → proxy to TMS_TRACKING_URL
"""

import os
from datetime import datetime, timezone, timedelta

import requests as http_requests
from fastapi import APIRouter, HTTPException, Query

router = APIRouter(prefix="/api/tracking", tags=["Tracking BFF"])

TRACKING_MODE        = os.getenv("TRACKING_MODE", "fixture")
TMS_TRACKING_URL     = os.getenv("TMS_TRACKING_URL", "")   # e.g. https://tms.example.com/api/tracking
TMS_ACCESS_KEY       = os.getenv("TMS_ACCESS_KEY", "")


# ─── Fixture (frozen contract shape — swap for real endpoint on integration day) ──

def _make_fixture(token: str) -> dict:
    now = datetime.now(timezone.utc)
    return {
        "token": token,
        "trip_id": "TRIP-FIXTURE-001",
        "status": "in_transit",
        "vehicle": {
            "plate": "กข-1234",
            "driver_name": "สมชาย ใจดี",
            "current_lat": 13.7563,
            "current_lng": 100.5018,
            "last_updated": now.isoformat(),
        },
        "eta": {
            "stop_id": "STOP-002",
            "address": "456 ถนนพระราม 4 กรุงเทพฯ",
            "estimated_arrival": (now + timedelta(minutes=35)).isoformat(),
            "planned_arrival":   (now + timedelta(minutes=30)).isoformat(),
        },
        "timeline": [
            {
                "event_type":  "wo.started",
                "occurred_at": (now - timedelta(hours=2)).isoformat(),
                "label":       "รถออกจากต้นทางแล้ว",
                "stop_id":     None,
            },
            {
                "event_type":  "stop.arrived",
                "occurred_at": (now - timedelta(hours=1)).isoformat(),
                "label":       "รถมาถึงจุดแรกแล้ว",
                "stop_id":     "STOP-001",
            },
            {
                "event_type":  "stop.delivered",
                "occurred_at": (now - timedelta(minutes=45)).isoformat(),
                "label":       "ส่งสินค้าจุดแรกเรียบร้อย",
                "stop_id":     "STOP-001",
            },
        ],
        "_fixture": True,  # flag so the frontend can show a dev banner
    }


# ─── Proxy ────────────────────────────────────────────────────────────────────

def _proxy(token: str) -> dict:
    if not TMS_TRACKING_URL:
        raise HTTPException(status_code=503, detail="TMS_TRACKING_URL not configured")
    try:
        resp = http_requests.get(
            f"{TMS_TRACKING_URL}",
            params={"token": token},
            headers={"Authorization": f"Bearer {TMS_ACCESS_KEY}"},
            timeout=10,
        )
        if resp.status_code == 404:
            raise HTTPException(status_code=404, detail="Tracking token not found or expired")
        resp.raise_for_status()
        return resp.json()
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"TMS unreachable: {e}")


# ─── Route ────────────────────────────────────────────────────────────────────

@router.get("")
async def get_tracking(token: str = Query(..., description="Short-lived tracking token")):
    """
    Returns the tracking read shape for the given token.
    This is the only endpoint the public tracking frontend calls.

    Integration day: set TRACKING_MODE=proxy and TMS_TRACKING_URL to switch
    from fixture to live data — no code changes required.
    """
    if not token:
        raise HTTPException(status_code=400, detail="token is required")

    if TRACKING_MODE == "proxy" and TMS_TRACKING_URL:
        return _proxy(token)

    return _make_fixture(token)
